os: WMF 5

version: 1.1.{build}
max_jobs: 1

environment:
  PSGALLERY_API_KEY:
    secure: qPAs23fYiJNou8sdbzm08y/azR3FTVzz/L54nbzg2C1pTrUtxN+IiDqEoSOu0gxu

  appveyor_rdp_password:
    secure: FkFUdBFp3f4+PKFV1bNoIQ==

branches:
  only:
  - master

skip_commits:
  message: /updated? readme.*s/

build: false

init:
- git config --global user.email "nobody@nothing.com"
- git config --global user.name "Nobody"
- git config --global core.safecrlf false
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - ps: |
      $env:PSModuleBuildScript = "$env:TEMP\indented.build\.build.ps1"
      'Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version'
      Get-ChildItem env:
      $PSVersionTable

  - git --version
  - choco --version

  - ps: |
      "Build info"
      '  {0,-20} {1}' -f 'SCHEDULED BUILD:', ($Env:APPVEYOR_SCHEDULED_BUILD -eq 'true')
      '  {0,-20} {1}' -f 'FORCED BUILD:'   , ($Env:APPVEYOR_FORCED_BUILD    -eq 'true')
      '  {0,-20} {1}' -f 'RE BUILD:'       , ($Env:APPVEYOR_RE_BUILD        -eq 'true')

  - ps: |
      $null = Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
      Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
      Install-Module InvokeBuild
      Set-Location $env:APPVEYOR_BUILD_FOLDER\$env:APPVEYOR_PROJECT_NAME
      git clone -q https://github.com/pauby/indented.build.git (Split-Path $env:PSModuleBuildScript -Parent) --single-branch --depth 1
      choco install pandoc -y --limit-output
      Update-Help -Force

build_script:
  - ps: |
      Invoke-Build InstallRequiredModules
      Invoke-Build -Task GetBuildInfo
      Invoke-Build

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
